# Generated by Django 5.0.6 on 2024-06-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=64)),
                ('name', models.CharField(default=None, max_length=64)),
                ('address', models.CharField(default=None, max_length=64)),
                ('overview', models.CharField(default=None, max_length=64)),
                ('rating', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('Sin', 'Single room'), ('Stn', 'Standard double room'), ('Del', 'Deluxe double room'), ('Stu', 'Studio room or apartment'), ('Jsu', 'Junior suite'), ('Psu', 'Presidential suite')], max_length=3)),
                ('beds', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('capacity', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotel')),
            ],
        ),
    ]
