# Generated by Django 5.0.6 on 2024-06-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_hotel_rating_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='chech_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='chech_out',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
