# Generated by Django 5.0.6 on 2024-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_booking_total_price_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
