# Generated by Django 4.2.13 on 2024-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Single', 'Single room'), ('Standard double', 'Standard double room'), ('Deluxe double', 'Deluxe double room'), ('Studio', 'Studio room or apartment'), ('Suite', 'Junior suite'), ('Presidential suite', 'Presidential suite')], max_length=24),
        ),
    ]
